### ISSUE TITLE
Win 7?

### ISSUE THREAD

**Issue by harryray33** [kacos2000/Evtx_Log_Browser#3]
Does this work with Win 7?

Thanks

**Comment by kacos2000** [comment]
Sorry , no it doesn't. 
Win 8.1 and above should be ok.

**Comment by harryray33** [comment]
Thanks, do any of the old releases work?

**Comment by kacos2000** [comment]
No, there isn't any difference, and I don't have Win7, Vista or Win 8 to test. These are obsolete..
